### ISSUE TITLE
Use of 'instanceof'

### ISSUE THREAD

**Issue by xogeny** [sgarciac/bombadil#1]
This library looks really interesting and I need something like this.  But potential issue I see is with the use of `instanceof` in discriminating your union types.  I've used a similar approach in libraries before and been bitten badly.  The issue arises when you instantiate instances of these classes from different packages/modules.  They will not end up with the same class so `instanceof` will fail in surprising and unintuitive ways.

My solution has been to rework the code to use discriminated unions with explicit tags.  I see no downside to this approach.  Is this something you'd accept a pull request for?

**Comment by sgarciac** [comment]
Hello, 
Sure, I see no reason not to if it improves the code

**Comment by bd82** [comment]
Same type of instances created in different iframes would also fail instanceOf check.

**Comment by xogeny** [comment]
I've created a pull request as #3, so I'm going to close this.
