### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by xogeny** [sgarciac/bombadil#2]
Would you accept a PR that included some tests?

**Comment by sgarciac** [comment]
hello, of course!

**Comment by xogeny** [comment]
Are you ok with Jest for the testing.  I think snapshots would be quite useful here and you'll get good code coverage stats out of the box.  Let me know if that is OK with you and I'll try to put something together.

**Comment by sgarciac** [comment]
I didn't know Jest, but it does look nice. I'd be nice to have some unit tests of individual functions indeed.

Notice that there is some code and a couple of scripts that test bombadil against https://github.com/BurntSushi/toml-test , which provides quite a good coverage, but only up to version 2.0 of the TOML spec.

**Comment by xogeny** [comment]
So I whipped up some quick Jest tests.  You can preview them in [my repo](https://github.com/xogeny/bombadil/blob/jest/test/toml.ts).  The output looks like this:

```
 PASS  test/toml.ts
  ✓ Example TOML (69ms)
  ✓ Fruit TOML (11ms)
  ✓ Hard Example TOML (17ms)
  ✓ Hard Example TOML (13ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   1 passed, 1 total
Time:        2.075s, estimated 3s
Ran all test suites.
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
All files    |    74.45 |    27.59 |    56.99 |    75.88 |                |
 AST.js      |    90.91 |      100 |    61.11 |    90.91 | 37,66,70,74,89 |
 bombadil.js |      100 |       50 |      100 |      100 |              3 |
 lexer.js    |    84.64 |     5.15 |    50.57 |    85.22 |... 383,393,403 |
 parser.js   |    62.18 |    53.85 |    58.06 |    66.92 |... 163,164,171 |
 tables.js   |     68.8 |    57.78 |      100 |    68.03 |... 235,236,238 |
 tools.js    |    42.22 |    16.67 |    41.67 |    42.22 |... 80,82,84,86 |
-------------|----------|----------|----------|----------|----------------|
```

I'm going to run them in conjunction with my modifications in #3 and make sure everything passes.

**Comment by xogeny** [comment]
OK, I added the `toml-test` cases.  But I see that four cases don't work.  It is a little hard to say for sure, but it appears that even with `master` if you run `bombadil-tester.sh`, you'll get JSON output that doesn't match what `toml-test` expects.

The tests that currently show differences are: `table-array-implicit`, `table-array-many`, `table-array-nest` and `table-array-one`.

Although 4 tests currently fail, the coverage stats for the working ones look like this:

```
 PASS  test/toml-spec.ts

Test Suites: 1 failed, 1 passed, 2 total
Tests:       4 failed, 37 passed, 41 total
Snapshots:   1 passed, 1 total
Time:        2.404s
Ran all test suites.
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
All files    |    81.98 |    36.14 |    67.37 |    82.97 |                |
 bombadil.ts |      100 |       50 |      100 |      100 |              3 |
 lexer.ts    |    84.64 |     5.15 |    50.57 |    85.22 |... 383,393,403 |
 parser.ts   |    83.59 |       60 |       80 |    86.63 |... 212,213,234 |
 tables.ts   |    73.02 |    74.36 |    93.33 |    72.73 |... 231,232,234 |
 tools.ts    |       80 |    83.33 |       75 |       80 |... 52,56,60,86 |
-------------|----------|----------|----------|----------|----------------|
```

I suspect the issue with the failing tests is actually only in how you convert back and forth between `toml-test` and your native representations.  The differences look like this:

```
 ● Running toml-test for table-array-one

    expect(received).toEqual(expected)

    Expected value to equal:
      {"people": [{"first_name": {"type": "string", "value": "Bruce"}, "last_name": {"type": "string", "value": "Springsteen"}}]}
    Received:
      {"people": {"type": "array", "value": [{"first_name": {"type": "string", "value": "Bruce"}, "last_name": {"type": "string", "value": "Springsteen"}}]}}

    Difference:

    - Expected
    + Received

    @@ -1,7 +1,9 @@
      Object {
    -   "people": Array [
    +   "people": Object {
    +     "type": "array",
    +     "value": Array [
            Object {
              "first_name": Object {
                "type": "string",
                "value": "Bruce",
              },
    @@ -9,6 +11,7 @@
                "type": "string",
                "value": "Springsteen",
              },
            },
          ],
    +   },
      }
```

**Do you want me to submit a PR so you can take a look at this?**

**Comment by sgarciac** [comment]
Very nice! Yes, please create a PR

**Comment by xogeny** [comment]
I just cracked the `toml-test` riddle as well.  I'll send you a PR in a few minutes that runs all the TOML spec and `toml-test` tests and passes for all of them.  Then I'll go back and confirm that my tagged union branch passes all tests as well.

**Comment by xogeny** [comment]
There are some common changes between the testing stuff and the tagged union stuff.  So what I'm going to do is push out a new version of tagged unions that includes the tests.  I'll keep independent branches around just in case you decide you want one and not the other.
