### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by xogeny** [sgarciac/bombadil#4]
I noticed the function `fromCodePoint` appears to expect a number.  But it is called as follows:

```javascript
  return fromCodePoint([parseInt(codeString, 16)]);
```

I don't see how to reconcile these except to remove the `[]`s from around the result returned by `parseInt`.

I located this because I turned `noImplicitAny` on in the code and make sure that nothing ended up with implicit types and this popped out as something where I couldn't find a consistent type for the function argument.

PS - with the suggested change (and several others), I was able to create a version of `bombadil` that doesn't include any implicit types and still passes 100% of tests from #2.  Shall I submit a PR with those changes and this fix?

**Comment by sgarciac** [comment]
eh! it does look like a bug, indeed!
Please see my comment on the PR
