### ISSUE TITLE
Failure to parse on integer value: 0

### ISSUE THREAD

**Issue by Mithradatha** [sgarciac/bombadil#6]
`reader.readToml('key = 0').result` = null
`reader.readToml('key = 0', true).result` = { key: { type: 'atomicInteger', image: '0', value: 0 } }

Not sure if this is intended behaviour, but it's inconsistent with the TOML specification.
By the way, the `errors` object is empty, even when getting a null `result`

The same thing does not happen with integer value: 1
`reader.readToml('key = 1').result` = { key: 1 }

**Comment by sgarciac** [comment]
ugh, such an ugly error!
It should be fixed now, thanks for reporting it.
