### ISSUE TITLE
table should extend null

### ISSUE THREAD

**Issue by LongTengDao** [sgarciac/bombadil#7]
```toml
toString = 1
```

This will make the parsing fail, and return null.

There is two way to fix this,

1.  use `hasOwnProperty`, not `in`
2.  use `Object.create(null)` to create a table, not `{}`

But the first way is slow, and can't deal with `__proto__` property, so the way 2 is better.

**Comment by sgarciac** [comment]
Sorry for the delay. Such a nasty bug, thanks for reporting

**Comment by sgarciac** [comment]
fixed

**Comment by sgarciac** [comment]
Yes, sorry, I forgot to push:

https://github.com/sgarciac/bombadil/commit/f0d8b0de38a641978980fae26903281d6b0c34e8
