### ISSUE TITLE
Would you like to collaborate?

### ISSUE THREAD

**Issue by bd82** [sgarciac/bombadil#8]
Hello @sgarciac 

I am working on a set of TOML tools here:
- https://github.com/bd82/toml-tools

Currently this includes a TOML Lexer/Parser using the latest Chevrotain Version.
- No transformer to JSON yet.

Perhaps you want to join efforts? 😄 

Cheers.
Shahar.

**Comment by sgarciac** [comment]
Hello! Sorry for not replying sooner! I'll have a look at it!

**Comment by bd82** [comment]
cheers 😄
